### PR TITLE
Feature defaults for interactive inputs

### PR DESCRIPTION
**Pull request by dewittpe**
Two additional arguments, re #244

### CODE REVIEW

**Comment by jtlangevin** [comment]
@dewittpe thanks for this request. I think the rationale for this adjustment makes sense, but that if we're going to implement it we should do so for all of the cmd line options that are currently interactive. Looking through the code, I believe that's the following:

adopt_scn_restrict
alt_regions
exog_hp_rates
grid_decarb
tsv_metrics

There are also a few new ones on the branch decarb-develop that may make their way into the next release. I think we should make these changes for all of those interactive options at once, here. Could that be done in a revision of this pull request?

**Comment by dewittpe** [comment]
@jtlangevin Yes, I can modify this PR.  I'll make some edits ping you when the additional args have been added.

**Comment by dewittpe** [comment]
@jtlangevin I've added arg for the other interactive sections listed and for the `retro_set` as well.    You may want to review 0583910 with more scrutiny than the other commits in this PR as that one makes a bigger change to the code base than the others to deal with the `mult_yr` value for `retro_sets`.

**Comment by trynthink** [comment]
Many changes to the Scout workflow and documentation have been implemented to address the request in this PR, including 89c82d8, d657c14, dc53dee, and others.

**Pull request closed without merging**
