### PR TITLE
Clean up, update, and expand geo mapping files

### PR DESCRIPTION
**Pull request by jtlangevin**
Updated all the mapping data [here](https://docs.google.com/spreadsheets/d/13n4abgODUrZ5w4CY1xrvg7APvNJtNVty8sPJn2vM4yU/edit?gid=565962725#gid=565962725) and reflected them in the Scout geo mapping files and baseline data, on top of @trynthink's fixes for the commercial data.

### CODE REVIEW

**Comment by jtlangevin** [comment]
@trynthink a note that I see some small negative values for `health care` building type in a few regions, and would appreciate if you can verify those negatives are present in the underlying EIA data.

e.g., for `new england` -> `health care` -> `electricity` -> `MELs` -> `other`:

```
"other": {
            "energy": {
              "2016": -1151449.0,
              "2017": -1288993.0,
              "2018": -1464411.0,
              "2019": -1444773.0,
              "2020": -113440.0,
              "2021": -120260.0,
              "2022": -124197.0,
              "2023": -156029.0,
              "2024": -155408.0,
              "2025": -152845.0,
              "2026": -150379.0,
              "2027": -149298.0,
              "2028": -148734.0,
              "2029": -148257.0,
              "2030": -147598.0,
              "2031": -147358.0,
              "2032": -147359.0,
              "2033": -148382.0,
              "2034": -158456.0,
              "2035": -158289.0,
              "2036": -166320.0,
              "2037": -167073.0,
              "2038": -172429.0,
              "2039": -173035.0,
              "2040": -173251.0,
              "2041": -173545.0,
              "2042": -173434.0,
              "2043": -173368.0,
              "2044": -172478.0,
              "2045": -171715.0,
              "2046": -171437.0,
              "2047": -171040.0,
              "2048": -171027.0,
              "2049": -169733.0,
              "2050": -168722.0
            },
            "stock": "NA"
          }
```

**Comment by trynthink** [comment]
> @trynthink a note that I see some small negative values for `health care` building type in a few regions, and would appreciate if you can verify those negatives are present in the underlying EIA data.
> 
> e.g., for `new england` -> `health care` -> `electricity` -> `MELs` -> `other`:
> 
> ```
> "other": {
>             "energy": {
>               "2016": -1151449.0,
>               "2017": -1288993.0,
>               "2018": -1464411.0,
>               "2019": -1444773.0,
>               "2020": -113440.0,
>               "2021": -120260.0,
>               "2022": -124197.0,
>               "2023": -156029.0,
>               "2024": -155408.0,
>               "2025": -152845.0,
>               "2026": -150379.0,
>               "2027": -149298.0,
>               "2028": -148734.0,
>               "2029": -148257.0,
>               "2030": -147598.0,
>               "2031": -147358.0,
>               "2032": -147359.0,
>               "2033": -148382.0,
>               "2034": -158456.0,
>               "2035": -158289.0,
>               "2036": -166320.0,
>               "2037": -167073.0,
>               "2038": -172429.0,
>               "2039": -173035.0,
>               "2040": -173251.0,
>               "2041": -173545.0,
>               "2042": -173434.0,
>               "2043": -173368.0,
>               "2044": -172478.0,
>               "2045": -171715.0,
>               "2046": -171437.0,
>               "2047": -171040.0,
>               "2048": -171027.0,
>               "2049": -169733.0,
>               "2050": -168722.0
>             },
>             "stock": "NA"
>           }
> ```

I did some spot checking and these negative values are consistent with the difference in the values reported by EIA in the commercial microdata files for total electric other energy use and the sum of all MELs energy use. I can't explain why there would be negative values like this, but it is consistent with the AEO data.

**Comment by trynthink** [comment]
@jtlangevin With this update to the geography mapping spreadsheet, there are eight geography translation files that are not included but continue to be used by `final_mseg_converter.py`.

1. Com_Cdiv_Czone_ColSums.txt
2. Com_Cdiv_Czone_RowSums.txt
3. Com_Cdiv_EMM_Elec_EU_RowSums.csv
4. Com_Cdiv_State_Elec_EU_RowSums.csv
5. Res_Cdiv_Czone_ColSums.txt
6. Res_Cdiv_Czone_RowSums.txt
7. Res_Cdiv_EMM_Elec_EU_RowSums.csv
8. Res_Cdiv_State_Elec_EU_RowSums.csv

How are these files updated? Do they need to be added as sheets in the spreadsheet?

**Comment by jtlangevin** [comment]
@trynthink that's right. 

The _EU_ ones are produced via post-processing EULP data (@handichan can comment more on the specific method used here.)

Com_Cdiv_EMM_Elec_EU_RowSums.csv
Com_Cdiv_State_Elec_EU_RowSums.csv
Res_Cdiv_EMM_Elec_EU_RowSums.csv
Res_Cdiv_State_Elec_EU_RowSums.csv

The _Cdiv_Czone_ ones were previously produced, but not via the geo mapping sheet. I wasn't able to track down exactly where those came from, but I believe it could have been based on an earlier version of RECS/CBECS data that included the AIA climate zones in the microdata (no longer included)

Com_Cdiv_Czone_ColSums.txt
Com_Cdiv_Czone_RowSums.txt
Res_Cdiv_Czone_ColSums.txt
Res_Cdiv_Czone_RowSums.txt

**Review by trynthink — APPROVED** [review]

**Pull request merged**
